env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    jsx: true
  sourceType: module
  project: "./tsconfig.json"
  ecmaVersion: 2018
plugins:
  - prettier
  - "@typescript-eslint/eslint-plugin"
  - sort-imports-es6-autofix
rules:
  prettier/prettier:
    - error
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  eqeqeq: error
