env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: [
  'prettier'
]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    jsx: true
  sourceType: module
  project: "./tsconfig.json"
  ecmaVersion: 2018
rules:
  radix: error
  eqeqeq: error
  "@typescript-eslint/no-explicit-any": off
